# Parameters

In [1]:
from datetime import datetime

dir_data = '/uufs/chpc.utah.edu/common/home/zpu-group30/cfeng/GOES-R-observation-error-covariance/03_HAFS/data'
case = '2021_AL09_Ida'
version = 'AS'
anl_start_time = datetime(2021, 8, 24, 0, 0, 0)
anl_end_time = datetime(2021, 8, 24, 0, 0, 0)
cycling_interval = 6

# Create BUFR Temp

In [2]:
from goes import create_goes_bufr_temp

create_goes_bufr_temp(dir_data=dir_data,
                      case=case,
                      anl_start_time=anl_start_time,
                      anl_end_time=anl_end_time,
                      cycling_interval=cycling_interval,
                      version=version)

Cycles: 0/1 files | 00:00<?

2021-08-23 21:00:00
2021-08-24 03:00:00
2021-08-24 00:00:20.200000
2021-08-24 00:09:52.100000
/uufs/chpc.utah.edu/common/home/zpu-group30/cfeng/GOES-R-observation-error-covariance/03_HAFS/data/GOES/2021_AL09_Ida/20210824/OR_ABI-L2-CMIPF-M6C07_G16_s20212360000202_e20212360009521_c20212360009592.nc


/uufs/chpc.utah.edu/common/home/u1237353/climetlab-my-plugin/functions/goes.py:138: RuntimeWarning: invalid value encountered in sqrt
  r_s   = (-1.0*b - np.sqrt(np.power(b, 2)-4*a*c))/(2*a)
/uufs/chpc.utah.edu/common/home/zpu-group30/cfeng/software/mymini3/lib/python3.9/site-packages/pyorbital/orbital.py:133: RuntimeWarning: invalid value encountered in sqrt
  rg_ = np.sqrt(rx * rx + ry * ry + rz * rz)


[2021 2021 2021 ... 2021 2021 2021]
[8 8 8 ... 8 8 8]
[24 24 24 ... 24 24 24]
[0 0 0 ... 0 0 0]
[5 5 5 ... 5 5 5]
[6.226907 6.226907 6.226907 ... 6.226907 6.226907 6.226907]
[81.15668487548828 81.09764099121094 81.03233337402344 ...
 -80.79076385498047 -80.86253356933594 -81.0622787475586]
[-79.28404998779297 -79.11976623535156 -78.95494079589844 ...
 -64.7054443359375 -64.48858642578125 -64.1099853515625]
[89.85332142321862 89.79253549462875 89.72552299947976 ...
 89.61185089439262 89.68880570127584 89.89628148230626]
[80.77462005615234 80.8125991821289 80.85242462158203 ...
 104.98790740966797 104.9901123046875 104.96151733398438]
[175.66392882578123 175.8295232307457 175.99564525438612 ...
 349.57226154660646 349.3548418324953 348.97766189274387]
[282.9276428222656 283.0983581542969 283.2705078125 ... 245.98330688476562
 245.74789428710938 245.31878662109375]
[35786023. 35786023. 35786023. ... 35786023. 35786023. 35786023.]
[0 0 0 ... 0 0 0]
[259.2942199707031 259.0846862792969 259.

KeyboardInterrupt: 

# Create BUFR File

In [ ]:
# from goes import create_goes_bufr_file

# create_goes_bufr_file(dir_data=dir_data,
#                       case=case,
#                       anl_start_time=anl_start_time,
#                       anl_end_time=anl_end_time,
#                       cycling_interval=cycling_interval,
#                       version=version)